// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdfedrujltnyloxpximh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkZmVkcnVqbHRueWxveHB4aW1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTk3OTksImV4cCI6MjA3MTE3NTc5OX0.r9xENBj8w8uleqQ7M6RyYRqe0aKbE6B82WU7H6ubWJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});